install! 'cocoapods', :warn_for_unused_master_specs_repo => false

use_frameworks!

platform :ios, '14.0'

target 'AppStart_Example' do
  pod 'AppStart', :path => '../'

  target 'AppStart_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  minimum = '14.0'
  projects = [installer.pods_project]
  projects.concat(installer.generated_projects.map(&:project)) if installer.respond_to?(:generated_projects)
  projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum
    end
    project.targets.each do |target|
      # Enable tracing resources
      if target.name == 'RxSwift'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum
      end
    end
  end
end
