install! 'cocoapods', :warn_for_unused_master_specs_repo => false

use_frameworks!

platform :ios, '14.0'

target 'AppStart_Example' do
  pod 'AppStart', :path => '../'

  target 'AppStart_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 10.0.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end

post_install do |installer|
  #base_config_setup(installer)
  installer.pods_project.targets.each do |target|
      # Enable tracing resources
      if target.name == 'RxSwift'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
          end
        end
      end
      #
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
  end
end
